### PR TITLE
Basic memory pressure status displaying as bar

### PR DESCRIPTION
**Pull request by geigi**
My attempt for a basic memory pressure feature. Memory pressure can be displayed as bar. It uses the 4 stages of memory pressure levels that are provided by the os. Localisation for other languages than english is missing.

Issue: #43

### CODE REVIEW

**Comment by yujitach** [comment]
Thanks for implementing it!  I have two comments before I can merge. 

1. I always used the pie chart instead of the bar, so it was not obvious for me until I read the source code that it's only activated inside the bar view. Please deactivate the checkbox if the bar type is not chosen.

2. Please at least add the checkbox with the English label to other localizations.

Again let me thank you for your efforts.

**Comment by geigi** [comment]
Cheers for your feedback! I will fix the issues in the next days :)

**Comment by geigi** [comment]
So I've fixed the two issues you mentioned :) I think it's now a fairly clean implementation for the first memory pressure feature. What do you think?

**Comment by yujitach** [comment]
Thanks, it's now merged. I'll bump the version number and make it public soon.

**Comment by geigi** [comment]
Cool, cheers! :)

**Comment by lukehamburg** [comment]
Nice feature.  I hope the updated binary is available from Yuji soon.

**Pull request merged**
