### PR TITLE
Added support for:

### PR DESCRIPTION
**Pull request by bji**
1. Horizontal thermometer bars for CPU usage
2. Sort CPU usage
3. Average lowest utilized half of CPUs into one bar

(1) allows for much more fidelity in CPU usage display - the wide horizontal
bars are much longer than the vertical bars and thus can show finer detail

(2) allows the CPU usage to be more easily tracked by eye

(3) allows a view of "hyperthreaded" CPUs that doesn't feature the
"virtual" cores as highly as the "real" cores, on the assumption that
the operating system will always schedule processes on 'physical' cores
before 'virtual' cores, thus the lower half of the CPUs are not 'real'
and can be averaged into one CPU bar to reduce clutter and yet still
give some insight into their usage.

### CODE REVIEW

**Comment by bji** [comment]
Hi there, thank you for bringing MenuMeters into the modern age with your changes that allow it to work on recent Mac OS X versions.

I created my own fork of MenuMeters in 2012 when I got my first Mac OS X system (the retina Macbook Pro that I am using right now!), because I wanted to add a few features.  Those features are described in the pull request above.  I didn't upgrade my version of OS X for *years* because I didn't like some of the changes that Apple had made, but finally last year sometime I updated ... and found that my MenuMeters had broken.

I didn't bother 'fixing' it until today, when I got your fork of MenuMeters and re-applied my original forked changes to it.

It would be so awesome if you could take my changes into your fork so that I could feel more confident that they will not break again unbeknownst to me.

The horizontal thermometers feature is I think a no-brainer: it really creates a much more dense CPU usage display that I find much more readable and pleasant (of course, it's an option, the vertical arrangement is still supported!).

The sorting by CPU usage feature is, I think, very nice too because it makes the whole thing much less 'busy' looking, and easier to read.  Of course it does misrepresent the situtation a *little bit* -- if a process jumps around between CPUs that won't be obvious, because of the sorting.  However, I find the idea of 'just show me how much CPU is being used regardless of which CPU is doing it' better matches my needs.  And again, it's only an option.

The 'average lowest half of CPUs to a single bar' feature is the most controversial.  I like to assume that the operating system will always schedule processes on individual physical cores before doubling up processes on the same core; so until the load hits 4, I would expect the cores being used to all be physical cores.  And these should each get their own cpu bar which is natural.  However, once we get past 4 loaded cores, the operating system will be doubling up processes on individual cores, which means that 'virtual' cores will start to be used.  I don't really want to see 'virtual' cores as real cores with real cpu bars because they're not real cores.  I just want to know if the system is so loaded that virtual cores are being utilized to a significant degree.  And so averaging the lowest half of the CPUs (by usage) into one bar seems reasonable to me -- it lets me see what are almost certainly the real physical cores as real bars, and all of the 'fluff' that is virtual cores in one more bar.  This allows me to have 5 bars in on my 4 physical/4 virtual core CPU instead of 8, which is much easier to discern.

And again -- it's only an option.

I updated all of the .nib files to include settings for all languages except chinese; I find the chinese one incomprehensible and didn't modify it.

Also, I am not an Objective-C programmer or a Mac programmer by trade so alot of this is very foreign to me and I may very well have done some things wrong -- especially the .nib file editing.  So feel free to correct anything yourself or to ask me to fix things, I will be happy to.


Thank you!

**Comment by bji** [comment]
Also, if you could merge in that other MenuMeters project where the Makefile was added, that thing is sooooo useful for building an installer.  It would be great.

https://github.com/emcrisostomo/MenuMeters

**Comment by bji** [comment]
Thank you for your fast handling of this!  If you need any help maintaining MenuMeters please just let me know.  Best wishes!

**Comment by bji** [comment]
I just tried it, I think I see what you mean.  Looks like it is repeating the graphs for all CPUs as the same.  I will investigate.

**Comment by bji** [comment]
Actually, looking more closely, it seems to be working.  I was seeing similar graphics because the process I was running (the build of MenuMeters) was loading all of the CPUs similarly.  But if I intentionally run processes one at a time to load the CPU I get the expected graphs.

Can you describe what you are seeing that seems broken?

**Comment by bji** [comment]
OK now I am trying "Show average for multiple processors as a single display" and *that* seems to be broken; it's only showing the first CPU instead of the average.  I will look into it.

**Comment by piadam** [comment]
Hello,

Any idea why I keep getting this?



> On Jul 23, 2018, at 11:23, yujitach <notifications@github.com> wrote:
> 
> Please work against the latest commit on my version. Thanks.
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

   _
 /_/  _/  _   ___
/ / (_/ (_/ / / /
 Adam van Gaalen (running macOS Mojave v10.14beta)

internet: adam@vangaalen.homeip.net
internet: adam.vangaalen@icloud.com
http    : http://www.vangaalen.homeip.net

**Comment by bji** [comment]
Keep getting what?

**Comment by piadam** [comment]
You probably missed my attachment:



> On Aug 5, 2018, at 17:38, bji <notifications@github.com> wrote:
> 
> Keep getting what?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

   _
 /_/  _/  _   ___
/ / (_/ (_/ / / /
 Adam van Gaalen (running macOS Mojave v10.14beta)

internet: adam@vangaalen.homeip.net
internet: adam.vangaalen@icloud.com
http    : http://www.vangaalen.homeip.net

**Comment by bji** [comment]
Yes; I'm sorry I guess I did, and I keep missing it, because I see no attachment in the email that I receive from github notifying me of your comment, nor do I see any attachment in this issue directly on github.

Can you describe your issue?

**Comment by bji** [comment]
Hm, the name "MenuMetersPfre.strings" looks like a misspelling of "MenuMetersPref.strings" ... yujitach recently consolidated a bunch of the resource files and it looks like he may have made a mistake?  Unfortunately I am not in a position right now to work on this, but perhaps yujitach could take a look.

**Comment by piadam** [comment]
sorry, my typo

> On Aug 5, 2018, at 18:39, bji <notifications@github.com> wrote:
> 
> Hm, the name "MenuMetersPfre.strings" looks like a misspelling of "MenuMetersPref.strings" ... yujitach recently consolidated a bunch of the resource files and it looks like he may have made a mistake? Unfortunately I am not in a position right now to work on this, but perhaps yujitach could take a look.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

   _
 /_/  _/  _   ___
/ / (_/ (_/ / / /
 Adam van Gaalen (running macOS Mojave v10.14beta)

internet: adam@vangaalen.homeip.net
internet: adam.vangaalen@icloud.com
http    : http://www.vangaalen.homeip.net

**Comment by yujitach** [comment]
@piadam Thanks for noticing it. Somehow, it didn't even compile on my machine when I re-launched Xcode today! Very weird.  It seems that Xcode got confused whether the localization files are in French.lproj vs fr.lproj etc. 

I edit the .xcodeproj file itself to make it refer to the existing files, so that XIB now compiles (again, at least on my machine.) Could you check that it works for you too?

**Comment by piadam** [comment]
Sorry Yujitach,

After simply cloning the project from github and doing (in Xcode) the 'Product -> Scheme -> PrefPane'-switch I still get the: /Users/adam/Documents/My Projects/MenuMeters/PrefPane/Base.lproj/MenuMetersPref.xib: The file “MenuMetersPref.strings” couldn’t be opened because there is no such file.

**Comment by yujitach** [comment]
Could you try compiling the pref pane anyway? Xcode seems to remember the previous bad state (even when freshly cloned from the git repo, but at least it compiles on my machine.

**Comment by piadam** [comment]
Build Succeeded!

Thanks! Up and running MenuMeters again!

> On Aug 6, 2018, at 06:08, yujitach <notifications@github.com> wrote:
> 
> Could you try compiling the pref pane anyway? Xcode seems to remember the previous bad state (even when freshly cloned from the git repo, but at least it compiles on my machine.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

Kind regards,
   _
 /_/  _/  _   ___
/ / (_/ (_/ / / /
 Adam van Gaalen (running macOS Mojave v10.14beta)

internet: adam@vangaalen.homeip.net
internet: adam.vangaalen@icloud.com
http    : http://www.vangaalen.homeip.net

**Pull request merged**
