### PR TITLE
Update version string in PrefPane

### PR DESCRIPTION
**Pull request by luckman212**
The version displayed at the bottom of the prefPane was still showing 1.9.3

### CODE REVIEW

**Comment by luckman212** [comment]
Thanks for the new release Yuji! Just a small correction...

**Comment by yujitach** [comment]
Dear @luckman212, thanks but that's not the right way to fix ;-p Please modify `-[MenuMetersPref mainViewDidLoad]` to dynamically modify the version string so that you don't have to update that entry in the Info.plist every time the version is updated.

**Comment by luckman212** [comment]
@yujitach I updated my patch. Hope this one is more satisfactory. You still need to update Info.plist because that is what Finder shows in the Get Info window.

**Comment by yujitach** [comment]
Ah, I didn't know that `CFBundleGetInfoString` is shown in Finder ... What should we do? Clearly, entering the same number in several places manually is *not* the right solution. Humans shouldn't do what machines could do. There seems to be something called Info.plist preprocessing, but I'm not sure what's the right approach here...

**Comment by dak180** [comment]
@yujitach Might I suggest [Autorevison](https://autorevision.github.io/blog/2015/03/16/Xcode); it is a tool designed for exactly this.
You set the version once as the git tag and it gives you that and many other pieces of revision info in a form that is easy to integrate in almost any way you might choose.

**Comment by emcrisostomo** [comment]
Using the `Info.plist` preprocessing is very easy and straight to the point for this kind of things. I submitted a pull request for a different functionality that also solves this problem as a side effect. (https://github.com/yujitach/MenuMeters/pull/51)

**Comment by yujitach** [comment]
Merged @emcrisostomo's version. Thank you so much.

**Pull request closed without merging**
