### PR TITLE
Add support to build on 10.15 and lower version SDKs

### PR DESCRIPTION
**Pull request by Tatsh**
Per conversation https://github.com/yujitach/MenuMeters/issues/271

https://github.com/macports/macports-ports/pull/13007

### CODE REVIEW

**Comment by yujitach** [comment]
Thanks but please don't remove `@available` clause from `isDark`. Your change would make the binary I build on the latest macOS crash on older macOS's.

**Comment by Tatsh** [comment]
> Thanks but please don't remove `@available` clause from `isDark`. Your change would make the binary I build on the latest macOS crash on older macOS's.

Should be fixed now.

**Comment by yujitach** [comment]
Thanks.

**Comment by Tatsh** [comment]
Thanks for the quick turnaround.

**Comment by mascguy** [comment]
Thank you both for the quick turnaround on this. Great stuff!

**Pull request merged**
