### PR TITLE
Add Makefile build and create DMG installer

### PR DESCRIPTION
**Pull request by emcrisostomo**
Hi,

Here is a pull request that:

* Adds a Makefile with targets that lets us create a DMG installer.
* Remove stale files (old installer targets that IMO are not relevant any longer).
* Redefines the `PrefPane` target to deploy the build in `/tmp`, from where the `pkg` and the `dmg` files are built.
* Use `Info.plist` preprocessing to fill in version and copyright.

Cheers,

Enrico

### CODE REVIEW

**Comment by onpaws** [comment]
It'll be really nice to have a DMG installer like the original version.
This sounds nice!

**Comment by yujitach** [comment]
For me downloading zip and double-clicking the expanded .prefPane is a simpler solution. Why do you want pkg and dmg? It's not a rhetorical question; I value your input. I just want to know why some people prefer pkg and dmg.

That said, with App Translocation in Sierra, I might need to move to *signed* dmg, see e.g. [here].(https://weblog.rogueamoeba.com/2016/06/29/sierra-and-gatekeeper-path-randomization/)
Does your pull request take care of this signing issue?

Another thing is that I prefer smaller, separate pull requests, for each different things involved. I need to carefully check what the code within Makefile does before merging the pkg- and dmg- creation part. But due to lack of time that would need at least a month, probably more. If you give me separate pull requests for Info.list preprocessing and for removing the obsolete installer codes, I would be willing to merge them first.

**Comment by emcrisostomo** [comment]
> For me downloading zip and double-clicking the expanded .prefPane is a simpler solution. Why do you want pkg and dmg? It's not a rhetorical question; I value your input. I just want to know why some people prefer pkg and dmg.

I wouldn't know, exactly. I guess some people feel "safer" or something along the lines.

> Does your pull request take care of this signing issue?

Nope, but I'll have a look at it.

> If you give me separate pull requests for Info.list preprocessing and for removing the obsolete installer codes, I would be willing to merge them first.

Ok, it should be possible to do that very quickly.

**Comment by emcrisostomo** [comment]
Since there are dependencies between change sets, I will push the PR about `Info.plist` preprocessing after #52 has been integrated.

**Comment by emcrisostomo** [comment]
I believe the dmg is not affected by translocation: the application is not run by double-clicking on it. Instead, a `pkg` installer is run and as far as I can tell it's installing the software properly, in the intended path.

**Comment by yujitach** [comment]
I was reading the details of the pull request, and have one question. At which point in the Makefile is the pref pane signed? I would like to have the pref pane, the pkg and the dmg properly signed. Is it done somewhere in a magical way?

At present, as I couldn't figure out how to keep signing info private while putting the code to GitHub, I'm leaving codesigning off within the Xcode private, and have a separate script which signs the binary and wrap it in the zip file, which I use to make MenuMeters public.

**Comment by emcrisostomo** [comment]
The Makefile isn't signing: we would have to modify it in order to do so, but it should be trivial to hook your script into it.

**Comment by emcrisostomo** [comment]
Merged this one into my fork's `master` branch. If you wanted to create a `Makefile` target to invoke your signing script, it should be trivial.

**Comment by yujitach** [comment]
@emcrisostomo Thanks always for your efforts, but as I don't see the need for DMG installer I won't merge this.

**Pull request closed without merging**
