### PR TITLE
Add top N CPU intensive processes to CPU Menu Meter

### PR DESCRIPTION
**Pull request by HofiOne**
Initial version that's ready for Pull Request

New features:
- Added option to display top N most CPU intensive processes in CPU Menu Meter
- Pref pane option to set N

### CODE REVIEW

**Comment by yujitach** [comment]
Thanks, but could you update the preference panes for other languages too?

**Comment by HofiOne** [comment]
Unfortunately my Japanese, French, etc. knowledge is equal to zero ;)
Or do you mean adding the placeholders? Or using translators like Google Translate?

**Comment by HofiOne** [comment]
ohhh, I see, the prefpane resources! ok, adding them...

**Comment by yujitach** [comment]
(I hesitated to merge yours since I wasn't very comfortable that your code runs "top" behind the scenes. I understand that that's inevitable, because there's no other way to get process infos from a non-system app...) Then I merged a pull request from another person. I'm very sorry that it conflicts with your changes of .nib files. We definitely need to move on to a more modern way of managing localized nib files.

**Comment by yujitach** [comment]
I now changed the .nib localization to the modern method. Could you modify the .nib file within Base localization? Then the change should be reflected in other languages automatically without translation; there shouldn't be any need to directly modify the files for each language.

**Pull request closed without merging**
